export const CustomDrawerPage = [
  {
    id: 1,
    title: 'Home',
    name: 'home',
    type: 'antdesign',
    route: 'HomeScreen',
  },
  {
    id: 9,
    title: 'Appointments',
    name: 'calendar',
    type: 'evilicon',
    route: 'PatientViewScreen',
  },
  {
    id: 2,
    title: 'Test Booking',
    name: 'thermometer',
    type: 'entypo',
    route: 'PatientHistoryScreen',
  },
  {
    id: 3,
    title: 'Orders',
    name: 'shoppingcart',
    type: 'antdesign',
    route: 'VitalScreen',
  },
  {
    id: 4,
    title: 'Consultaions',
    name: 'user-nurse',
    type: 'font-awesome-5',
    route: 'LabReportScreen',
  },
  {
    id: 5,
    title: 'My Doctors',
    name: 'doctor',
    type: 'fontisto',
    route: 'RadiologyReportScreen',
  },
  {
    id: 6,
    title: 'Medical Records',
    name: 'briefcase-medical',
    type: 'font-awesome-5',
    route: 'MedicationTopTab',
  },
  {
    id: 7,
    title: 'My Insurance Policy',
    name: 'policy',
    type: 'materialicons',
    route: 'NursecallScreenDrawer',
  },
  {
    id: 8,
    title: 'Reminders',
    name: 'clock',
    type: 'entypo',
    route: 'PatientCallScreen',
  },

  {
    id: 10,
    title: 'Payments',
    name: 'creditcard',
    type: 'antdesign',
    route: 'ReportToAdminScreen',
  },
  {
    id: 11,
    title: 'Sign out',
    name: 'logout',
    type: 'antdesign',
    route: 'AlertScreen',
  },
];
